### ISSUE TITLE
Expose a DS.Errors compatible API

### ISSUE THREAD

**Issue by musaffa** [adopted-ember-addons/ember-cp-validations#175]
Currently `this.get(user, 'validations.errors')` returns an array of error objects. But calling errors with [DS.Errors](http://emberjs.com/api/data/classes/DS.Errors.html) returns an Ember Object.

``` handlebars
{{#each model.errors.username as |error|}}
  <div class="error">
    {{error.message}}
  </div>
{{/each}}
```

In this implementation, we can call `username` attribute on the object returned by `errors`. The most of the form addons conforms to this API. It would be nice if `ember-cp-validations` follows the same convention. It will make the integration with form addons much easier.

**Comment by offirgolan** [comment]
Thanks for opening up this issue. You can access specific attribute validations via `model.get('validations.attrs.username.errors')`

or in your template via 

```hbs
{{#each (v-get model 'username' 'errors') as |error|}}
  <div class="error">
    {{error.message}}
  </div>
{{/each}}
```

**Comment by musaffa** [comment]
@offirgolan Unfortunately almost all the form addons, for example ember-form-for (see [implemenation](https://github.com/martndemus/ember-form-for/blob/master/addon/templates/components/form-field.hbs#L8)), ember-simple-form (see [implementation](https://github.com/DockYard/ember-easy-form/blob/1-0-stable/addon/components/internal-input-for.js#L96)), implements DS.Errors like API. If ember-cp-validations could expose the similar error API, it could support the form addons out of the box.

I don't want to create another form addon and sometimes it is not possible to override the addon templates. So all the developers are left to do is to create another form addon or an adapter which will convert `ember-cp-validations` errors to DS.Errors compatible error object. What if `ember-cp-validations` already solves the problem for them?

Thanks.

**Comment by offirgolan** [comment]
I understand the use-case for this, but as of right now, I dont see the way the `validations` object is structured to change. If we were to have an `errors` object on the model, it will not only overwrite ember-data DS.Error implementation, but will have residual effects for any platform that is dependent on it. The validation object needs to be its own entity to not clash with any existing implementations. 

One proposal was to populate the DS.Error object with this library's messages (see #157). Unfortunately, I have yet to explore this option. Maybe once I have some free time. In the mean time, I would suggest taking a look at [ember-bootstrap-cp-validations](https://github.com/offirgolan/ember-bootstrap-cp-validations). 

If you have an idea about how to best solve this issue without restructuring the entire API, feel free to let me know and we can try to put something together.

**Comment by musaffa** [comment]
Another option can be a DS.Errors like errors object under `validations`namespace.

Not only polluting errors object of the model is a bad idea, mutating model instance in the form itself is a bad idea. Model instances should be immutable.

**Comment by musaffa** [comment]
@offirgolan Off topic, is it possible to know whether an attribute has any validator?

**Comment by offirgolan** [comment]
> Another option can be a DS.Errors like errors object under validationsnamespace. I wont solve the problem but will ease the pain a lot.

I feel like the easiest way to solve your problem is just to do the following in your model

```js
validationErrors: computed('validations.errors.[]', function() {
  return _.groupBy(this.get('validations.errors'), e => e.get('attribute'));
})
```

> is it possible to know whether an attribute has any validator?

If an attribute does not have any validators, then it will not be part of the `validations.attrs` object

**Comment by musaffa** [comment]
> Maybe I can add something similar to the validations object.

:+1:

**Comment by musaffa** [comment]
> If an attribute does not have any validators, then it will not be part of the validations.attrs object

Is it possible to check for the presence of any specific validator on an attribute. For example, I want to determine whether the field is required (to put a * in the label) dynamically based the presence of the `Presence` validator.

**Comment by rwwagner90** [comment]
Closing some old issues as wontfix for now. If this issue is still relevant, please feel free to open a new one!
