### ISSUE TITLE
How to validate checkbox, selectbox and radiobutton in ember-cp-validations

### ISSUE THREAD

**Issue by arunprasath416** [adopted-ember-addons/ember-cp-validations#496]
### Environment

- Ember Version: 
- Ember CLI Version:
- Ember CP Validations Version:

### Steps to Reproduce

I am using ember-cp-validation in ember js application for validation. I want to validate _checkbox_, _selectbox_ and _radiobutton_. I can't find any sample code to validate these controls.

Can anybody give any ideas/sample on how to validate 

> checkbox
, 
> selectbox 

and 

> radiobutton 

using ember-cp-validation plugin.

**Comment by stephanebruckert** [comment]
I've given a solution for a checkbox here https://stackoverflow.com/a/44434195/1515819

**Comment by fsmanuel** [comment]
@arunprasath416 I'm closing the issue because it's quite old. Feel free to reopen if you need more help.
