### ISSUE TITLE
Ember Cp validation on model

### ISSUE THREAD

**Issue by sainigurpreet** [adopted-ember-addons/ember-cp-validations#509]
### Environment

- Ember Version: 2.13.0
- Ember CLI Version:
- Ember CP Validations Version:

Hello,

I am new to ember js. i facing problem while implementing ember-cp-validation. i don't know where i am doing something wrong? my code is given below:

My js file for creating new record.
**route/new.js**

import Ember from 'ember';
export default Ember.Route.extend({
  model() {
    return this.store.createRecord('signup')
  },
  submit() {
    let Name  = this.controller.get('model.Name');
    let Email   = this.controller.get('model.Email');
    let Password      = this.controller.get('model.Password');
    let account1      = this.store.createRecord('signup', {
      Name: Name,
      Email: Email,
      Password: Password,
      account: this.get('currentUser.account'),
    });

    account1.save().then(() => {
      Ember.Logger.log('save successful');
    this.controller.set('model.Name',null);
    this.controller.set('model.Email',null);
    this.controller.set('model.Password',null);
    this.flashMessages.success("account creation was successful");

  });
  },
});

Model for new user:
**models/signup.js**
import Ember from 'ember';
import DS from 'ember-data';
import { validator, buildValidations } from 'ember-cp-validations';

const Validations = buildValidations({

  Name: {
    validators: [
      validator('presence', true),
      validator('length', {
        max: 30
      })
    ]
  },
  Email: {
    validators: [
      validator('presence', true),
      validator('format', { type: Email }),
      validator('length', {
        max: 200,
      })
    ]
  },
  Password: {
    description: 'Password',
    validators: [
      validator('presence', true),
      validator('length', {
        min: 4,
        max: 30
      }),
      validator('format', {
        regex: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{4,10}$/,
        message: '{description} must include at least one upper case letter, one lower case letter, and a number'
      }),
    ]
  },
  details: validator('belongs-to')
}, {
  debounce: 500
});

export default DS.Model.extend(Validations,{
  Name: DS.attr('string'),
  Email: DS.attr('string'),
  Password: DS.attr('string')

});

Template for creating new user
Template/new.hbs
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
</head>

<br>
<h1 style="height: 30px; text-align:center">Register</h1>
<form>
  <div class="form-group">
    <label> Name</label>
    {{validated-input valuePath='Name' placeholder="Enter Your Name"  tabindex=1 model=signup  }}
  </div>
  <div class="form-group">
    <label>Email</label>
    {{validated-input  valuePath='Email' placeholder="Enter Your Email"  tabindex=2  model=signup }}
  </div>
  <div class="form-group">
    <label>Password</label>
    {{validated-input  valuePath='Email' placeholder="Enter Your Email"  tabindex=2  model=signup }}
  </div>
  <button  class="btn btn-default"  {{action "submit"}}>Create Account</button>
</form>
<br>
<h2>Gridview</h2>
<div class="form-group">
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
    </tr>
    </thead>
    <tbody>
    {{#each model as |signup|}}
      <tr>
        <td>{{signup.Name}}</td>
        <td>{{signup.Email}}</td>
        <td>{{signup.Password}}</td>
      </tr>
    {{/each}}
    </tbody>
  </table>
</div>

component(template)
**component/validated-input.hbs**

<div class="form-group">
  {{input type=type value=value placeholder=placeholder
          class="form-control" name=valuePath }}
  {{#if isValid}}
    <span class="valid-input fa fa-check" style="color: green"></span>
  {{/if}}

  <div class="input-error">
    {{#if showMessage}}
      <div class="error">
        <p style="color: red; font-size:12px; margin:0;">{{v-get model
                                                                 valuePath 'message'}}</p>
      </div>
    {{/if}}
  </div>
</div>

Js file of created component
**component/validatedinput.js**

import Ember from 'ember';

const {
  computed,
  defineProperty,
} = Ember;

export default Ember.Component.extend({

  classNames: ['validated-input'],
  classNameBindings: ['showErrorClass:has-error', 'isValid:has-success'],
  model: null,
  value: null,
  type: 'text',
  valuePath: '',
  placeholder: '',
  validation: null,
  isTyping: false,

  init() {
    this._super(...arguments);
    var valuePath = this.get('valuePath');
    defineProperty(this, 'validation', computed.oneWay(`model.validations.attrs.${valuePath}`));
    defineProperty(this, 'value', computed.alias(`model.${valuePath}`));
  },

  notValidating: computed.not('validation.isValidating'),
  didValidate: computed.oneWay('targetObject.didValidate'),
  hasContent: computed.notEmpty('value'),
  isValid: computed.and('hasContent', 'validation.isValid', 'notValidating'),
  isInvalid: computed.oneWay('validation.isInvalid'),
  showErrorClass: computed.and('notValidating', 'showMessage', 'hasContent', 'validation'),
  showMessage: computed('validation.isDirty', 'isInvalid', 'didValidate', function() {
    return (this.get('validation.isDirty') || this.get('didValidate')) && this.get('isInvalid');
  })
});

Please help me where i am doing wrong 
Thanks in advance

**Comment by acorncom** [comment]
@sainigurpreet did you get this resolved?  If so, might be worth closing this issue ...

**Comment by fsmanuel** [comment]
@sainigurpreet I'm closing the issue because it's quite old. Feel free to reopen if you need more help.
