### ISSUE TITLE
isValid doesn't become false using $.ajax instead of default .save()

### ISSUE THREAD

**Issue by stephanebruckert** [adopted-ember-addons/ember-cp-validations#514]
### Environment

- Ember Version: 2.13.1
- Ember CLI Version: 2.13.1
- Ember CP Validations Version: 3.3.2

##### Model + validation

```
const Validations = buildValidations({
  username: {
    description: 'Username',
    validators: [
      validator('exclusion', {
        in: Ember.computed(function() {
          return this.get('model').alreadyTakenUsernames;
        }).volatile(),
        message: 'Already taken'
      })
    ]
  }
});

export default DS.Model.extend(Validations, {
  username: DS.attr('string'),

  alreadyTakenUsernames: [],

  setAlreadyTakenUsername: function(justTaken) {
    this.get('alreadyTakenUsernames').push(justTaken);
  }
});
```

##### Controller

```
actions: {
    validate() {
      this.get('model').validate().then(({ validations }) => {
        let self = this;
        this.set('didValidate', true);

        if (validations.get('isValid')) {
          let username = this.get('model').get('username');
          this.get('model').save().then(() => {
             // anything
          }).catch(() => {
             self.get('model').setAlreadyTakenUsername(username);
          });
        }
      });
    }
  }
```

When I click "validate", it does `.save()` on my model and it adds one more used username to the `alreadyTakenUsernames` array (let's assume all usernames are taken).

And it works, as soon as I click "submit", the username field becomes red (`has-error`).

#### And now this doesn't exactly work (should do the same thing)

If in my model I override `.save()` to do an `$.ajax` call:

 ```
 save: function() {
    let data = {
      username: this.get('username')
    };
    return new Promise(function (resolve, reject) {
      $.ajax({
        dataType: 'json',
        data: JSON.stringify({ data: { attributes: data, type: "users" }}), <-- I'm doing JSONAPI
        type: 'POST',
        headers: {
          'accept': ENV.APP.vendorVersion,
          'content-type': ENV.APP.jsonContentType
        },
        success: function(response) {
          resolve(response);
        },
        error: function(xhr) {
          reject(xhr);
        }
      });
    });
  }
```

With a bit of tweaking I managed to get exactly the same responses between `$.ajax` and `.save()`, but still when I use `$.ajax`, `isValid` would be `true` and the fields don't show `has-error` whereas it should. It only gets `has-error` if I remove and add one character, for example:

 - username is `stephane`
 - click "submit"
 - username doesn't have `has-error`
 - change username to be `stephan`
 - change username to be `stephane`
 - username gets `has-error`

Whereas with `save()` it just works:

 - username is `stephane`
 - click "submit"
 - username gets `has-error`
 
Maybe `.save()` has an extra step that `ember-cp-validations` expects, a kind of "attributes refresh".

I would really appreciate some help on this one. If ^ doesn't help much, I can try to isolate the situation in a repo or fiddle, but first I wanted to know whether I wasn't forgetting anything silly. Thanks!

**Comment by stephanebruckert** [comment]
Okay I'm going to implement on-the-fly uniqueness validation such as exposed here https://github.com/offirgolan/ember-cp-validations/issues/125. I didn't want to do this at first for security purposes, as there is no way to involve a captcha. But I just saw Twitter does this too.

I would still find an answer to this issue interesting! Otherwise if the answer isn't obvious, feel free to close.

**Comment by fsmanuel** [comment]
@stephanebruckert I'm closing the issue because it's quite old. Feel free to reopen if you still need help.
