### ISSUE TITLE
 select-dropdown component

### ISSUE THREAD

**Issue by jsamuel89** [adopted-ember-addons/ember-cp-validations#572]
### Environment

- Ember Version:  
- Ember CLI Version: 2.18.2
- Ember CP Validations Version: 3.x

First of all thanks for great addon.!!
I am finding difficulty with validations against select-dropdown component.
Can someone point me to example with all the HTML elements covered??

Thanks in advance.
P.S This is not a issue!!

**Comment by fsmanuel** [comment]
@jsamuel89 I'm closing the issue because it's quite old. Feel free to reopen if you still need help.
