### ISSUE TITLE
Set validation to `true` manually for a particular model field

### ISSUE THREAD

**Issue by rinoldsimon** [adopted-ember-addons/ember-cp-validations#582]
### Environment

- Ember Version: 2.18.0
- Ember CLI Version: 2.18.0
- Ember CP Validations Version: 4.0.0-beta.0

### Steps to Reproduce
    start_year: [
     validator('inline', {
      validate(value, options, model) {
        if (model.get('start_year') && model.get('end_year')) {
          // end_year should be greater than or equal to start_year
          return this.get('model.end_year') < value ? "Start year should be less than or equal to End year" : true;
        } else {
          return true;
        }
      }
    })

    end_year: [
     validator('inline', {
      validate(value, options, model) {
        if (model.get('start_year') && model.get('end_year')) {
          // start_year should be lesser than or equal to end_year
          return value < this.get('model.start_year') ? "End year should be greater than or equal to Start year" : true;
        } else {
          return true;
        }
      }
    })

In the above scenario, it throws validation message when it is not Valid. Then after changing the values of `start_year` to a `valid year` the validation message still remains for `end_year` and vice versa.

we can't use `model.set('validations.attr.end_year.isValid, true')` once `start_year` is changed to a `valid year`, since it is a `read-only` property. 

Is there any other way to fix it ?

**Comment by fsmanuel** [comment]
@rinoldsimon I'm closing the issue because it's quite old. Feel free to reopen if you still need help.
