### ISSUE TITLE
Ember data models are fully re-validated when they should not be

### ISSUE THREAD

**Issue by panthony** [adopted-ember-addons/ember-cp-validations#592]
### Environment

- Ember Version: 3.0.0
- Ember CLI Version: 3.0.0
- Ember CP Validations Version: 4.0-beta

### Steps to Reproduce

Not sure if it's an `ember-cp-validations` issue or an `ember-data` issue but I'm creating the issue here in case someone stumble upon the same thing to avoid wasting time.

I have an `ember-data` model with some validations rules on its properties.

When I update one of its property (making it valid/invalid etc.), it will occasionally re-trigger ALL the validations of all the model.

After some digging it turned out this is because `didChange` is called for the `isDeleted` property which, in turn, clear all the cached validations.

Now my `ember-data` is in a saved state and I'm not deleting it so I don't know why `isDeleted` is notified as being changed.

Probably because of https://github.com/emberjs/data/issues/966

Any idea how `ember-cp-validations` could handles deleted models without depending on `isDeleted` ?

It was added by https://github.com/offirgolan/ember-cp-validations/pull/312

**Edit:**

Full story:

When the model move in and out its dirty state the `isDeleted` flag is also invalidated, this causes the model to fully revalidate.

**Comment by offirgolan** [comment]
Hi @panthony! Thanks for all the detail in the issue you opened! Unfortunately, there isnt much I can do from the this addon 😞. 
 
The reason CPs are dependent on `isDeleted` is so validations will not be run on deleted ember data models which have caused a good amount of issues in the past.

> Any idea how ember-cp-validations could handles deleted models without depending on isDeleted?

Honestly I'm not entirely sure. `isDeleted` is really the only available public API that has been around since the early days. There could be some other private workaround but it would have to be ported to every single ember-data version.

**Comment by panthony** [comment]
@offirgolan If you remember the kind of errors there was in the past, do you think I can be fine if I remove the `isDeleted` from dependent key as long as I'm using only "hard" delete (`destroyRecord`) and never soft deletes?

Because I also saw in CPs that there is a `isValidatable` that make sure `isDeleted`  is false because calling the validation in the model.

My guess is that the validations will never be called on a deleted model anyway but of soft deleted model could stay in error state since it wouldn't be re-validated (and cleared of errors) but in my case I do not have such use case.

**Comment by fsmanuel** [comment]
@panthony I'm closing the issue because it's quite old. Feel free to reopen if you still need help.
