### ISSUE TITLE
model.validate is not a function

### ISSUE THREAD

**Issue by interlochen** [adopted-ember-addons/ember-cp-validations#613]
### Environment

- Ember Version: 
- Ember CLI Version:
- Ember CP Validations Version:

### Steps to Reproduce
It seems like several people are having the same issue with some being able to fix it and some not. None of the solutions I have found have been able to help me fix this.

I have a model defined as such:        

        import DS from 'ember-data';
        import { validator, buildValidations } from 'ember-cp-validations';

        const Validations = buildValidations({
	        weapon: validator('presence', {
		        presence: true,
		        message: 'please enter a weapon name'
	        }),
        });

        export default DS.Model.extend(Validations, {
	        weapon: DS.attr('string'),
	        gold: DS.attr('number'),
	        silver: DS.attr('number'),
	        copper: DS.attr('number'),
	        damageDie: DS.attr('number'),
	        damageType: DS.attr('string'),
	        amountDice: DS.attr('number'),
	        weight: DS.attr('string'),
	        properties: DS.attr('string'),
        });

I then use my route to give access in my controller:

        export default Route.extend({
	        model: function () {
		        return Ember.RSVP.hash({
			        weapon: this.store.findAll('weapon'),
			        spell: this.store.findAll('spell'),
			        armor: this.store.findAll('armor'),
		})
	   },

       setupController(controller, model) {
		this._super(...arguments);
		Ember.set(controller, 'weapon', model.weapon);
		Ember.set(controller, 'spell', model.spell);
		Ember.set(controller, 'armor', model.armor);
	   }

And then I have the action set up in my controller:

        addWeapon: function(weapon) {
            //grab form info here
			
		let weaponName = this.get('weaponName');
		let gold = this.get('gold');
		let silver = this.get('silver');
		let copper = this.get('copper');
		let weaponDie = this.get('weaponDie');
		let damageType = this.get('damageType');
		let weaponAmount = this.get('weaponAmount');
		let weight = this.get('weight');
		let properties = this.get('properties');

		let newWeapon = this.store.createRecord('weapon', {
			weapon: weaponName,
			gold: gold,
			silver: silver,
			copper: copper,
			damageDie: weaponDie,
			damageType: damageType,
			amountDice: weaponAmount,
			weight: weight,
			properties: properties
		});

		//weapon = this.get('weapon');
		console.log(weapon);

		weapon.validate()
			.then( ({validations}) => {
				console.log(validations)
				if(validations.get('isValid')) {
					console.log('form is valid')
					//newWeapon.save();
				}else{
					console.log(validations.get('isValid'))
					console.log(validations.get('isInvalid'))
				}
			})

			

		this.setProperties({
			weaponName: null,
			gold: null,
			silver: null,
			copper: null,
			weaponDie: null,
			damageType: null,
			weaponAmount: null,
			weight: null,
			properties: null
		});
	}

In the template I pass the weapon model that I set up. Console logging the model seems to work, but within log the model does not seem to contain the function. However, if I log the newWeapon record I just created, it does contain the methods. I am really confused about this part. 

When I call the action it tells me that weapon.validate, where weapon is the model, is not a function. Am I defining something incorrectly somehwere, or am I misunderstanding how the models are being accessed?

**Comment by fsmanuel** [comment]
@interlochen I'm closing the issue because it's quite old. Feel free to reopen if you still need help.
