### ISSUE TITLE
`value` method executes multiple times

### ISSUE THREAD

**Issue by sumeetattree** [adopted-ember-addons/ember-cp-validations#622]
### Environment

- Ember Version: 3.6.0
- Ember CLI Version: 3.6.0
- Ember CP Validations Version: 4.0.0-beta.5

First off thanks for the amazing library! Getting it up and running was a breeze. 
Now on to my query, (what the title says).
Here's my use case
```js
  ...
  language: validator('inclusion', {
    in: reads('model.i18n.locales'),

    dependentKeys: ['model.locale'],
    // value: reads('model.locale') <- this is what I expected
    value(model) {
      console.log('validating language against ', model.locale); // This will execute multiple times. In my example I have this wired up with an `ember-power-select` input
      return model.locale;
    },
  });
```
Is there any specific reason as to why value can't be a `computed` property instead? I would have expected it to be a computed property, especially since we have to pass in `dependentKeys` as a separate option. Am I missing something?

**Comment by fsmanuel** [comment]
@sumeetattree I'm closing the issue because it's quite old. Feel free to reopen if you still need help.
