### ISSUE TITLE
deprecation warning ember 3.9 - computed-property.volatile 

### ISSUE THREAD

**Issue by fran-worley** [adopted-ember-addons/ember-cp-validations#639]
### Environment

- Ember Version: 3.9.0
- Ember CLI Version: 3.9.0
- Ember CP Validations Version: 4.0.0-beta.8

### Steps to Reproduce

When running ember app with the above addon versions we get the following deprecation error:

Setting a computed property as volatile has been deprecated. Instead, consider using a native getter with native class syntax. [deprecation id: computed-property.volatile]

**Comment by BitBrit** [comment]
This sounds like it's linked to: [#638](https://github.com/offirgolan/ember-cp-validations/issues/638)

**Comment by viniciussbs** [comment]
Replacing the computed by a getter as suggested [here](https://github.com/ember-cli/eslint-plugin-ember/blob/6483e934bfbcf5b64f46eb4077c54085c8ed9de2/docs/rules/no-volatile-computed-properties.md) does not work.

**Comment by fsmanuel** [comment]
@fran-worley @BitBrit @viniciussbs That should be fixed in the latest release. I'm closing the issue but feel free to reopen if the problem still exists.
