### ISSUE TITLE
ember-cli-changelog triggers a babel 5.x deprecation

### ISSUE THREAD

**Issue by locks** [adopted-ember-addons/ember-cp-validations#645]
I was messing around with the library and noticed while running tests that ember-cli-changelog triggers the deprecation for babel 5.x.
Given it is sort of in maintenance mode, this addon might want to move off of ember-cli-changelog to address the deprecation?

**Comment by Turbo87** [comment]
FYI https://github.com/html-next/ember-cli-changelog !== https://github.com/ember-cli/ember-cli-changelog 😉

**Comment by locks** [comment]
Dear lord xD

**Comment by fsmanuel** [comment]
We droped ember-cli-changelog and are about to use rwjblue-release-it-setup https://github.com/adopted-ember-addons/ember-cp-validations/pull/721
