### ISSUE TITLE
Installing this addon breaks build on Ember 4

### ISSUE THREAD

**Issue by JenLyndle** [adopted-ember-addons/ember-cp-validations#701]
### Environment

- Ember Version: 4.0.1
- Ember CLI Version: 4.0.1
- Ember CP Validations Version: 4.0.0

### Steps to Reproduce
Create a brand new ember app on the latest Ember and install ember-cp-validations addon. Run ember build. It will break with the error:

WARNING: [DEPRECATION] [DEPRECATION] Usage of the Ember Global is deprecated. You should import the Ember module or the specific API instead.

See https://deprecations.emberjs.com/v3.x/#toc_ember-global for details.

Usages of the Ember Global may be caused by an outdated ember-cli-babel dependency. The following steps may help:

* Upgrade the following addons to the latest version:
  * ember-cp-validations

### Important ###

In order to avoid repeatedly showing the same deprecation messages, no further deprecation messages will be shown for usages of the Ember Global until ember-cli-babel is upgraded to v7.26.6 or above.

To see all instances of this deprecation message, set the `EMBER_GLOBAL_DEPRECATIONS` environment variable to "all", e.g. `EMBER_GLOBAL_DEPRECATIONS=all ember test`.

### Details ###

Prior to v7.26.6, ember-cli-babel sometimes transpiled imports into the equivalent Ember Global API, potentially triggering this deprecation message indirectly, even when you did not observe these deprecated usages in your code.

The following outdated versions are found in your project:

* ember-cli-babel@6.18.0, currently used by:
  * ember-require-module@0.3.0
    * Depends on ember-cli-babel@^6.9.2
    * Added by ember-cp-validations@4.0.0-beta.12
    * Added by ember-cp-validations@4.0.0-beta.12 > ember-validators@3.0.1
  * ember-validators@3.0.1
    * Depends on ember-cli-babel@^6.9.2
    * Added by ember-cp-validations@4.0.0-beta.12

Environment: development
cleaning up...
Template Compiler Error (TemplateCompiler) in ember-quickstart/templates/application.hbs

Cannot read properties of undefined (reading 'visitor')

Stack Trace and Error Report: /var/folders/7l/54hcgmcj5px90x_b3n2lkss00000gn/T/error.dump.230e7976d87f3c46c3e6cfa1b4b3edcb.log

**Comment by odanylevskyi** [comment]
I am getting the same error. Any update on this? Thanks
