### ISSUE TITLE
Documentation site no longer exists

### ISSUE THREAD

**Issue by jarrodn-au** [adopted-ember-addons/ember-cp-validations#707]
### Environment

- Ember Version: any
- Ember CLI Version: any
- Ember CP Validations Version: 4+

### Steps to Reproduce

1. Open http://offirgolan.github.io/ember-cp-validations/docs in a web browser
2. Observe the 404 status page

**Comment by mrloop** [comment]
This is fixed in #708

#### [Live Demo](http://adopted-ember-addons.github.io/ember-cp-validations)

#### [Documentation 4.x](http://adopted-ember-addons.github.io/ember-cp-validations/docs)
