### ISSUE TITLE
Setup release, changelog, etc according to the guidelines

### ISSUE THREAD

**Issue by fsmanuel** [adopted-ember-addons/ember-cp-validations#720]
To comply with the adopted-ember-addons org [guidelines](https://github.com/adopted-ember-addons/program-guidelines) we should setup the:
- [ ] [release](https://github.com/adopted-ember-addons/program-guidelines#release-process) process https://github.com/adopted-ember-addons/ember-cp-validations/pull/721
- [ ] [changelog](https://github.com/adopted-ember-addons/program-guidelines#changelog) process https://github.com/adopted-ember-addons/ember-cp-validations/pull/721

**Comment by fsmanuel** [comment]
@knownasilya If you give me maintainer access I can do the setup for the release and changelog process

**Comment by knownasilya** [comment]
Should have write access now

**Comment by fsmanuel** [comment]
Thanks. Will work on it over the weekend.
